version: '3.3'
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HEADER_HOST: 'http://localhost:8081/remoteEntry.js'
    ports:
      - '8082:8080'
